[package]
name = "mutsuki"
version = "0.1.0"
authors = ["DESKTOP-2CTP7F6\\xutia <853122726@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log4rs = "1"
log = "0.4"
hyper = { version = "0.14", features = ["full"] }
base64 = "0.13"
socket2 = "0.4"
tokio-rustls = "0.23"
futures-util = "0.3"
rustls-pemfile = "0.2"
once_cell = "1.9"
parking_lot = "0.11"

[profile.release]
lto = true
codegen-units = 1
